import MainLayoute from "@/components/layoutes";
import { Inter } from "@next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import { HomePage } from "../components/index";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Demo | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayoute>
          <HomePage />
        </MainLayoute>
      </main>
    </>
  );
}
